### ISSUE TITLE
Ova r0-.2 default password

### ISSUE THREAD

**Issue by b4b857f6ee** [VultureProject/vulture-base#1]
Hi,

I cannot find the default password for the ova
For the vlt-adm account for ssh. 

Thank you.

**Comment by jjourdin** [comment]
Hi,

Default password for vlt-adm is "vlt-adm". 
Once logged as root, please get the latest version via "pkg update" then "pkg upgrade".

Jérémie

**Comment by b4b857f6ee** [comment]
So simple....
Thank you.
Don't forget to add it in the ReadMe :)

thank you.
