### ISSUE TITLE
Logging is OFF

### ISSUE THREAD

**Issue by cri57ian** [VultureProject/vulture-base#17]
Hello,

After updating and bootstrapping Vulture 4.0, the logging option has a red indicator. All the others are green.

Tried several times, but always get the same result.

Anyway you can help me, guys?

Thanks in advance.

**Comment by NRGLine4Sec** [comment]
Do you update from Vulture 3 to Vulture 4 ?

**Comment by cri57ian** [comment]
No.. tried like 50 times this recipe:

- fresh BSD install as it says in building.md ( zfs filesystem, bla bla )
- followed the guide exactly

So, all were working except LOGGING. 

I used the update button ( from the admin console), most of the updates failed but now logging is working. On the other hand, AI framework seems to be off, but that is quite often and will eventually kick back in.

So.. Seems the update ( even though mostly failed) fixed the issue.

Another thing is... After a while of using it, i get GATEWAY TIMEOUT and i am not able to restore it so i have to either use a backup or start fresh, as per my first paragraph.

Thanks for your help.
