### ISSUE TITLE
Default password for OVA ?

### ISSUE THREAD

**Issue by Firzum** [VultureProject/vulture-base#3]
Hello,

I have downloaded the OVA for vulture, installed it in VMWare ESX, started the VM, which is using DHCP. Sadly I doon't have a DHCP in this vlan, so i would like to open a session from VMWARE console. To ba able to do that, I will need the default password for vlt-adm,  which is not available into the documentation.

Do I missed something ?

Thanks in advance.

Regards,

N.B. Une réponse en français me convient aussi.

**Comment by KGuillemot** [comment]
Hello,

The default password of vlt-adm is vlt-adm.

You can then use the command *admin* to manage your VultureOS configuration, 
and follow the readme.

Regards,

Kevin

**Comment by Firzum** [comment]
Many thanks !
