### ISSUE TITLE
iso files checksums?

### ISSUE THREAD

**Issue by thetuxinator** [VultureProject/vulture-base#35]
Hi,

sorry had no idea where to put this, where can we get md5/sha256 checksums for the iso files?

kind regards

Tuxinator

**Comment by thetuxinator** [comment]
no info on this?

**Comment by thetuxinator** [comment]
Any feedback? Its quite an important topic.

**Comment by frikilax** [comment]
Sorry, this issue had gone unnoticed
you can already obtain sha256 from *.mf files
