### ISSUE TITLE
There is no .ISO in https://download.vultureproject.org/v4/12.0/isos/

### ISSUE THREAD

**Issue by NRGLine4Sec** [VultureProject/vulture-base#9]

**Comment by b4b857f6ee** [comment]
If you wan to install it from zero. Follow the guide. Just install a freebsd and follow the guide :).

**Comment by jjourdin** [comment]
Yes, "isos" is a mispelling. 
=> We are providing ready-to-run image for main hypervisors (do not hesitate to ask for specific one).

We won't provide bootable ISO.
